### PR TITLE
keep the input sequence is same as printing.  

### PR DESCRIPTION
**Pull request by dongchch2016**
Now the first input barcode will appear last in the print position, need to correct this bug.

### CODE REVIEW

**Comment by mgobat** [comment]
I'm not sure if this is working as you expect. In my test case, inputting the the four barcodes

- AUTO123
- 83280
- 54994
- abcdefg

results in the list

- 54994
- AUTO123
- 83280
- abcdefg

**Comment by dongchch2016** [comment]
Hi,Mgobat,

I found this line:45 of scan.component.ts: const barcodes = file.split(/\r\n|\n/)
      .reverse() /* Preserve order */
I don't think that's what we want. This line causes the barcodes in the file to be read in the opposite order as they are actually intended to be printed. 
can we remove line 45? ‘.reverse()'

chenchen

**Comment by mgobat** [comment]
@dongchch2016, fixed for the next release. Thank you.

**Comment by dongchch2016** [comment]
OK. Thank you!

chenchen

**Pull request merged**
